---
- hosts: all
  gather_facts: True
  vars_files:
    - vars/main.yaml
    - vars/bonding.yaml
    - vars/volumes.yaml
  roles:
    - common
    - laggyluke.add-ssh-keys-from-github
    - volumes
    - bonding
