centos_configs:
  - ifcfg-mgmt
  - ifcfg-vmnet
  - ifcfg-storage
  - ifcfg-em1
  - ifcfg-em3
  - ifcfg-p1p1
  - ifcfg-p1p2
  - ifcfg-p3p1
  - ifcfg-p3p2

centos_interfaces:
  - em1
  - em3
  - p1p2
  - p3p2
  - p1p1
  - p3p1

ubuntu_interfaces:
  - eth0
  - eth2
  - eth4
  - eth6
gateway: 10.127.101.1
netmask: 255.255.255.0
dns_search: sat6.lab

volume_group: vg_storage
physical_drive: /dev/sdb

add_ssh_keys_from_github:
    usernames:
      - cjoelrun
      - xeregin
      - jacobwagner
