---
- name: install pip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: pkg=python-pip state=installed

- name: install pip
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: pkg=$item state=installed
  with_items:
    - python-pip
    - libselinux-python